LB2D: lb::lattice Class Reference
lb::lattice Class Reference
Lattice containing the populations.
#include <lattice.hpp>
Public Types
typedef std::vector< node >
::iterator node_iterator
Iterator type.
typedef std::vector< node >
::const_iterator const_node_iterator
Const iterator type.
typedef std::vector< node >
::reverse_iterator reverse_node_iterator
Reverse iterator type.
typedef std::vector< node >
::const_reverse_iterator const_reverse_node_iterator
Const reverse iterator type.
Public Member Functions
lattice (unsigned int _nx, unsigned int _ny)
Construct the lattice with given extent.
unsigned int index (int i, int j) const
Convert a coordinate to a unique index.
node_iterator begin ()
Iterator pointing to the beginning.
const_node_iterator begin () const
Const iterator pointing to the beginning.
node_iterator end ()
Iterator pointing to the end.
const_node_iterator end () const
Const iterator pointing to the end.
reverse_node_iterator rbegin ()
Reverse iterator pointing to the end.
const_reverse_node_iterator rbegin () const
Const reverse iterator pointing to the end.
reverse_node_iterator rend ()
Reverse iterator pointing to the beginning.
const_reverse_node_iterator rend () const
Const reverse iterator pointing to the beginning.
node & get_node (int i, int j)
Get node at coordinate (i,j)
const node & get_node (int i, int j) const
Get node at coordinate (i,j)
node & get_node (unsigned int idx)
Get node at coordinate (i,j)
const node & get_node (unsigned int idx) const
Get node at coordinate (i,j)
void add_wall (coordinate< int > min_coord, coordinate< int > max_coord)
Add a solid wall.
void delete_walls ()
Delete all existing walls.
void write_fields (std::string file_name)
Write fields to file.
Public Attributes
const unsigned int nx
extent in x direction (excluding buffers)
const unsigned int ny
extent in y direction (excluding buffers)
const unsigned int size
total number of nodes (excluding buffers)
const unsigned int buffer_size
buffer width (equal to one)
const unsigned int real_nx
extent in x direction including buffers
const unsigned int real_ny
extent in y direction including buffers
const unsigned int real_size
total number of nodes including buffers
const unsigned int n_populations
number of populations
std::vector< std::vector
< float_type > > f
population data
std::vector< float_type > rho
density data
std::vector< float_type > u
flow x-velocity data
std::vector< float_type > v
flow y-velocity data
std::vector< node > nodes
array holding all node objects
std::vector< node > wall_nodes
array holding node objects belonging to a solid wall
property_array properties
properties datastructure (can hold many different properties per node)
const bool periodic_x
flag whether to use periodicity in x direction
const bool periodic_y
flag whether to use periodicity in y direction
Friends
std::ostream & operator<< (std::ostream &os, const lattice &l)
print to output stream, useful for debugging only
Detailed Description
Lattice containing the populations.
The lattice is constructed using the function velocity_set() which returns a velocity set object. Hence, the number of populations is defined through that function. Data structures are set up accordingly.
The basic data structure for the population and the macroscopic qunatities are one dimensional arrays (vectors) interpreted as two dimensional planes. The x (i) dimension varies first and the y (j) dimension last.
This class does provide access to the data through node iterators or through direct access of the public members. The node iterators return a node object that provides easy access to all local quantities according to the 2d lattice coordinate.
There are buffer regions (extent is one in all directions) around the data to make the advection procedure easier.
The data is indexed in the range [0, nx-1][0, ny-1]; including buffers indices span the range [-1, nx][-1, ny], repectively.
Definition at line 209 of file lattice.hpp.
Constructor & Destructor Documentation
lb::lattice::lattice (unsigned int _nx, unsigned int _ny)
Construct the lattice with given extent.
Parameters:
[in] _nx Number of nodes in x direction
[in] _ny Number of nodes in y direction
Definition at line 396 of file lattice.hpp.
References buffer_size, index(), nodes, properties, real_nx, real_ny, lb::property_array::register_flag_property(), and lb::property_array::set_flag_property().
Member Function Documentation
unsigned int lb::lattice::index (int i, int j) const [inline]
Convert a coordinate to a unique index.
Parameters:
[in] i x coordinate
[in] j y coordinate
Returns:
unique index
Precondition:
Coordinates are in the domain
Definition at line 432 of file lattice.hpp.
References buffer_size, and real_nx.
Referenced by lattice().
lattice::node_iterator lb::lattice::begin ()
Iterator pointing to the beginning.
Returns:
iterator
Definition at line 423 of file lattice.hpp.
References nodes.
lattice::const_node_iterator lb::lattice::begin () const
Const iterator pointing to the beginning.
Returns:
const iterator
Definition at line 424 of file lattice.hpp.
References nodes.
lattice::node_iterator lb::lattice::end ()
Iterator pointing to the end.
Returns:
iterator
Definition at line 425 of file lattice.hpp.
References nodes.
lattice::const_node_iterator lb::lattice::end () const
Const iterator pointing to the end.
Returns:
const iterator
Definition at line 426 of file lattice.hpp.
References nodes.
lattice::reverse_node_iterator lb::lattice::rbegin ()
Reverse iterator pointing to the end.
Returns:
reverse iterator
Definition at line 427 of file lattice.hpp.
References nodes.
lattice::const_reverse_node_iterator lb::lattice::rbegin () const
Const reverse iterator pointing to the end.
Returns:
const reverse iterator
Definition at line 428 of file lattice.hpp.
References nodes.
lattice::reverse_node_iterator lb::lattice::rend ()
Reverse iterator pointing to the beginning.
Returns:
reverse iterator
Definition at line 429 of file lattice.hpp.
References nodes.
lattice::const_reverse_node_iterator lb::lattice::rend () const
Const reverse iterator pointing to the beginning.
Returns:
const reverse iterator
Definition at line 430 of file lattice.hpp.
References nodes.
node & lb::lattice::get_node (int i, int j) [inline]
Get node at coordinate (i,j)
Parameters:
[in] i x coordinate
[in] j y coordinate
Returns:
reference to node at coordinate (i,j)
Precondition:
coordinates are in domain
Definition at line 434 of file lattice.hpp.
References buffer_size, nodes, and real_nx.
Referenced by add_wall(), and lb::simulation::initialize().
const node & lb::lattice::get_node (int i, int j) const [inline]
Get node at coordinate (i,j)
Parameters:
[in] i x coordinate
[in] j y coordinate
Returns:
const reference to node at coordinate (i,j)
Precondition:
coordinates are in domain
Definition at line 436 of file lattice.hpp.
References buffer_size, nodes, and real_nx.
node & lb::lattice::get_node (unsigned int idx) [inline]
Get node at coordinate (i,j)
Parameters:
[in] idx unique node index
Returns:
reference to node at coordinate (i,j)
Precondition:
idx is between [0, lattice::real_size)
Definition at line 438 of file lattice.hpp.
References nodes.
const node & lb::lattice::get_node (unsigned int idx) const [inline]
Get node at coordinate (i,j)
Parameters:
[in] idx unique node index
Returns:
const reference to node at coordinate (i,j)
Precondition:
idx is between [0, lattice::real_size)
Definition at line 440 of file lattice.hpp.
References nodes.
void lb::lattice::add_wall (coordinate< int > min_coord, coordinate< int > max_coord)
Add a solid wall.
Creates wall flags in the coordinate rectangle defined by min_coord and max_coord. The corresponding nodes get the flag "wall" and they are also stored in the vector lattice:wall_nodes for convienience.
Parameters:
[in] min_coord minimum bounding rectangle corner
[in] max_coord maximum bounding rectangle corner
Precondition:
(min_coord, max_coord) define a rectangle
Both min_coord and max_coord are in the domain
Definition at line 470 of file lattice.hpp.
References get_node(), lb::coordinate< T >::i, lb::coordinate< T >::j, lb::node::set_flag_property(), and wall_nodes.
void lb::lattice::write_fields (std::string file_name)
Write fields to file.
Write macroscopic variables to simple ascii file.
Parameters:
[in] file_name file name
Definition at line 496 of file lattice.hpp.
References buffer_size, nodes, nx, ny, real_nx, rho, u, and v.
Referenced by lb::simulation::write_fields().
The documentation for this class was generated from the following file:
lattice.hpp