LB2D: lb::property_array Class Reference
lb::property_array Class Reference
This class allows you to store properties in an array.
#include <property_array.hpp>
Public Types
typedef unsigned long int size_type
enumeration and size type
Public Member Functions
property_array (size_type size)
Construct with array size.
property_array (const property_array &other)
Copy construct.
void swap (property_array &other)
Swap internal state.
property_array & operator= (property_array other)
Assignement.
~property_array ()
bool register_flag_property (std::string name, bool set=false)
register a new flag property
template<typename T >
bool register_data_property (std::string name, bool set=false, const T &value=T())
register a new data property
bool set_flag_property (std::string name, size_type array_index)
set flag property
template<typename T >
bool set_data_property (std::string name, size_type array_index, const T &property)
set data property
bool set_flag_property (size_type property_index, size_type array_index)
set flag property
template<typename T >
bool set_data_property (size_type property_index, size_type array_index, const T &property)
set data property
bool unset_flag_property (std::string name, size_type array_index)
unset flag property
bool unset_data_property (std::string name, size_type array_index)
unset data property
bool unset_flag_property (size_type property_index, size_type array_index)
unset flag property
bool unset_data_property (size_type property_index, size_type array_index)
unset data property
template<typename T >
T & get_data_property (std::string name, size_type array_index)
access data property object
template<typename T >
const T & get_data_property (std::string name, size_type array_index) const
access data property object
template<typename T >
T & get_data_property (size_type property_index, size_type array_index)
access data property object
template<typename T >
const T & get_data_property (size_type property_index, size_type array_index) const
access data property object
bool flag_property_index (std::string name, size_type &property_index) const
get flag property index from flag property name
bool data_property_index (std::string name, size_type &property_index) const
get data property index from data property name
bool flag_property_name (size_type property_index, std::string &name) const
get flag property name from flag property index
bool data_property_name (size_type property_index, std::string &name) const
get data property name from data property index
size_type size () const
property array size
size_type num_flag_properties () const
number of registered flag properties
size_type num_data_properties () const
number of registered data properties
size_type num_properties () const
number of registered flag and data properties
bool has_flag_property (std::string name, size_type array_index) const
Check whether flag property is set.
bool has_data_property (std::string name, size_type array_index) const
Check whether data property is set.
bool has_flag_property (size_type property_index, size_type array_index) const
Check whether flag property is set.
bool has_data_property (size_type property_index, size_type array_index) const
Check whether data property is set.
bool count_set_flag_properties (std::string name, size_type &count) const
count flag properties which are set
bool count_set_data_properties (std::string name, size_type &count) const
count data properties which are set
bool count_set_flag_properties (size_type property_index, size_type &count) const
count flag properties which are set
bool count_set_data_properties (size_type property_index, size_type &count) const
count data properties which are set
bool exist_data_property (std::string name) const
check whether data property exists
bool exist_flag_property (std::string name) const
check whether flag property exists
Friends
std::ostream & operator<< (std::ostream &os, const property_array &pa)
print to output stream
Detailed Description
This class allows you to store properties in an array.
For every index in the property array you can register several flag properties (boolean values) and several custom objects of any type. As long as you do not store a data property for a given index no space will be used.
Example usage for flag property:
        property_array pa(5);                                            // property array of size 5
        pa.register_register_flag_property("test_flag",false);           // register a flag with name "test_flag", default value false
        pa.set_flag_property("test_flag",2);                             // set the flag at position 2 to true
        // alternatively you can use the property index
        property_array::size_type idx;
        pa.flag_property_index("test_flag", idx);
        pa.set_flag_property(idx,2);                                     // set the flag at position 2 to true
        bool value = pa.has_flag_property("test_flag",2);                // get the value at position 2 for your flag
        // using the index
        value = pa.has_flag_property(idx,2);                             // get the value at position 2 for your flag
        pa.unset_flag_property("test_flag",2);                           // set flag at position 2 to false
        // using the index
        pa.unset_flag_property(idx,2);                                   // set flag at position 2 to false
Example usage for data property:
        property_array pa(5);                                                           // property array of size 5
        // assume you want to store a std::vector<float>
        pa.register_register_data_property<std::vector<float> >("some_data",false);     // register a data property with name "some_data", default value: null
        std::vector<float> test_property(9,1.0);
        pa.set_data_property("some_data", 3, test_property);                            // store data property "some_data" at position 3 to be equal to variable test_property
        // again you could use an index instead of a string to access the property
        property_array::size_type idx;
        pa.data_property_index("some_data", idx);
        pa.set_data_property("some_data", 3, test_property);
        if (pa.has_data_property("some_data", 3))                                       // check whether there is a data property stored at index 3
        {
                std::vector<float> return_value;
                return_value=pa.get_data_property<std::vector<float> >("some_data",3);  // retrieve the data property
        }
        pa.unset_data_property("some_data", 3);                                         // delete the data property at index 3
Definition at line 158 of file property_array.hpp.
Constructor & Destructor Documentation
lb::property_array::property_array (size_type size) [inline]
Construct with array size.
Parameters:
[in] size array size
Definition at line 191 of file property_array.hpp.
lb::property_array::~property_array () [inline]
Destruct
Definition at line 231 of file property_array.hpp.
References num_data_properties().
Member Function Documentation
bool lb::property_array::register_flag_property (std::string name, bool set = false) [inline]
register a new flag property
Parameters:
[in] name flag property name
[in] set default state
Returns:
true if property does not exist yet
Definition at line 251 of file property_array.hpp.
Referenced by lb::lattice::lattice().
template<typename T > bool lb::property_array::register_data_property (std::string name, bool set = false, const T & value = T()) [inline]
register a new data property
Template Parameters:
T type for data property
Parameters:
[in] name data property name
[in] set default behaviour: initialized or null
[in] value value for default initialization
Returns:
true if property does not exist yet
Definition at line 269 of file property_array.hpp.
bool lb::property_array::set_flag_property (std::string name, size_type array_index) [inline]
set flag property
Parameters:
[in] name flag property name
[in] array_index position in array
Returns:
true if flag property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 288 of file property_array.hpp.
Referenced by lb::lattice::lattice(), and lb::node::set_flag_property().
template<typename T > bool lb::property_array::set_data_property (std::string name, size_type array_index, const T & property) [inline]
set data property
Template Parameters:
T type for data property
Parameters:
[in] name data property name
[in] array_index position in array
[in] property data to store
Returns:
true if data property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 305 of file property_array.hpp.
Referenced by lb::node::set_data_property().
bool lb::property_array::set_flag_property (size_type property_index, size_type array_index) [inline]
set flag property
Parameters:
[in] property_index flag property index
[in] array_index position in array
Returns:
true if flag property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 327 of file property_array.hpp.
References num_flag_properties().
template<typename T > bool lb::property_array::set_data_property (size_type property_index, size_type array_index, const T & property) [inline]
set data property
Template Parameters:
T type for data property
Parameters:
[in] property_index data property index
[in] array_index position in array
[in] property data to store
Returns:
true if data property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 343 of file property_array.hpp.
References num_data_properties().
bool lb::property_array::unset_flag_property (std::string name, size_type array_index) [inline]
unset flag property
Parameters:
[in] name flag property name
[in] array_index position in array
Returns:
true if flag property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 364 of file property_array.hpp.
Referenced by lb::node::unset_flag_property().
bool lb::property_array::unset_data_property (std::string name, size_type array_index) [inline]
unset data property
Parameters:
[in] name data property name
[in] array_index position in array
Returns:
true if data property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 378 of file property_array.hpp.
Referenced by lb::node::unset_data_property().
bool lb::property_array::unset_flag_property (size_type property_index, size_type array_index) [inline]
unset flag property
Parameters:
[in] property_index flag property index
[in] array_index position in array
Returns:
true if flag property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 400 of file property_array.hpp.
References num_flag_properties().
bool lb::property_array::unset_data_property (size_type property_index, size_type array_index) [inline]
unset data property
Parameters:
[in] property_index data property index
[in] array_index position in array
Returns:
true if data property exists
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 413 of file property_array.hpp.
References num_data_properties().
template<typename T > T& lb::property_array::get_data_property (std::string name, size_type array_index) [inline]
access data property object
Template Parameters:
T data property type
Parameters:
[in] name data property name
[in] array_index position in array
Returns:
reference to data property object
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 438 of file property_array.hpp.
Referenced by lb::node::get_data_property().
template<typename T > const T& lb::property_array::get_data_property (std::string name, size_type array_index) const [inline]
access data property object
Template Parameters:
T data property type
Parameters:
[in] name data property name
[in] array_index position in array
Returns:
const reference to data property object
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 459 of file property_array.hpp.
template<typename T > T& lb::property_array::get_data_property (size_type property_index, size_type array_index) [inline]
access data property object
Template Parameters:
T data property type
Parameters:
[in] property_index data property index
[in] array_index position in array
Returns:
reference to data property object
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 480 of file property_array.hpp.
References num_data_properties().
template<typename T > const T& lb::property_array::get_data_property (size_type property_index, size_type array_index) const [inline]
access data property object
Template Parameters:
T data property type
Parameters:
[in] property_index data property index
[in] array_index position in array
Returns:
const reference to data property object
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 501 of file property_array.hpp.
References num_data_properties().
bool lb::property_array::flag_property_index (std::string name, size_type & property_index) const [inline]
get flag property index from flag property name
Parameters:
[in] name flag property name
[out] property_index flag property index
Returns:
true if property exists
Definition at line 521 of file property_array.hpp.
bool lb::property_array::data_property_index (std::string name, size_type & property_index) const [inline]
get data property index from data property name
Parameters:
[in] name data property name
[out] property_index data property index
Returns:
true if property exists
Definition at line 534 of file property_array.hpp.
bool lb::property_array::flag_property_name (size_type property_index, std::string & name) const [inline]
get flag property name from flag property index
Parameters:
[in] property_index flag property index
[out] name flag property name
Returns:
true if property exists
Definition at line 547 of file property_array.hpp.
References num_flag_properties().
bool lb::property_array::data_property_name (size_type property_index, std::string & name) const [inline]
get data property name from data property index
Parameters:
[in] property_index data property index
[out] name data property name
Returns:
true if property exists
Definition at line 559 of file property_array.hpp.
References num_data_properties().
bool lb::property_array::has_flag_property (std::string name, size_type array_index) const [inline]
Check whether flag property is set.
Parameters:
[in] name flag property name
[in] array_index position in array
Returns:
true if property is set
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 586 of file property_array.hpp.
Referenced by lb::node::has_flag_property().
bool lb::property_array::has_data_property (std::string name, size_type array_index) const [inline]
Check whether data property is set.
Parameters:
[in] name data property name
[in] array_index position in array
Returns:
true if property is set
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 600 of file property_array.hpp.
Referenced by lb::node::has_data_property().
bool lb::property_array::has_flag_property (size_type property_index, size_type array_index) const [inline]
Check whether flag property is set.
Parameters:
[in] property_index flag property index
[in] array_index position in array
Returns:
true if property is set
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 614 of file property_array.hpp.
References num_flag_properties().
bool lb::property_array::has_data_property (size_type property_index, size_type array_index) const [inline]
Check whether data property is set.
Parameters:
[in] property_index data property index
[in] array_index position in array
Returns:
true if property is set
Precondition:
array_index is in range [ 0, property_array::size())
Definition at line 627 of file property_array.hpp.
References num_data_properties().
bool lb::property_array::count_set_flag_properties (std::string name, size_type & count) const [inline]
count flag properties which are set
Parameters:
[in] name flag property index
[out] count number of flag properties set
Returns:
true if flag property exists
Definition at line 639 of file property_array.hpp.
bool lb::property_array::count_set_data_properties (std::string name, size_type & count) const [inline]
count data properties which are set
Parameters:
[in] name data property name
[out] count number of data properties set
Returns:
true if data property exists
Definition at line 657 of file property_array.hpp.
bool lb::property_array::count_set_flag_properties (size_type property_index, size_type & count) const [inline]
count flag properties which are set
Parameters:
[in] property_index flag property index
[out] count number of flag properties set
Returns:
true if flag property exists
Definition at line 675 of file property_array.hpp.
References num_flag_properties().
bool lb::property_array::count_set_data_properties (size_type property_index, size_type & count) const [inline]
count data properties which are set
Parameters:
[in] property_index data property index
[out] count number of data properties set
Returns:
true if data property exists
Definition at line 692 of file property_array.hpp.
References num_data_properties().
bool lb::property_array::exist_data_property (std::string name) const [inline]
check whether data property exists
Parameters:
[in] name data property name
Returns:
true if exists
Definition at line 708 of file property_array.hpp.
bool lb::property_array::exist_flag_property (std::string name) const [inline]
check whether flag property exists
Parameters:
[in] name flag property name
Returns:
true if exists
Definition at line 719 of file property_array.hpp.
The documentation for this class was generated from the following file:
property_array.hpp