LB2D: lb::simulation Class Reference
lb::simulation Class Reference
Simulation class implementing LB.
#include <simulation.hpp>
Public Member Functions
simulation (unsigned int nx, unsigned int ny, float_type _Re, float_type _Vmax)
Construct from domain size and flow parameters.
void initialize ()
Initialize the flow field.
void advect ()
advect the populations
void wall_bc ()
apply wall boundary conditions
void collide ()
collide the populations
void step ()
LB step.
void write_fields ()
Public Attributes
lattice l
lattice
std::vector< int > shift
amount of nodes to shift each population in data structure during advection
const float_type Re
Reynolds number.
const float_type Vmax
mean flow velocity
const float_type visc
viscosity
const float_type beta
LB parameter beta.
unsigned int time
simulation time
bool file_output
flag whether to write files
unsigned int output_freq
file output frequency
unsigned int output_index
index for file naming
Friends
std::ostream & operator<< (std::ostream &os, const simulation &sim)
Detailed Description
Simulation class implementing LB.
This class holds a lattice as member (see simulation::l) and carries out the simulation steps on top of it. The main methods of this class are simulation::advect() and simulation::collide().
Definition at line 24 of file simulation.hpp.
Constructor & Destructor Documentation
lb::simulation::simulation (unsigned int nx, unsigned int ny, float_type _Re, float_type _Vmax) [inline]
Construct from domain size and flow parameters.
Parameters:
[in] nx extent in x direction
[in] ny extent in y direction
[in] _Re Reynolds number
[in] _Vmax mean flow velocity
Definition at line 35 of file simulation.hpp.
References shift, lb::v9::size, and lb::velocity_set().
Member Function Documentation
void lb::simulation::initialize () [inline]
Initialize the flow field.
Initialization includes defining initial density, velocity and populations. You can use Taylor-Green vortex flow conditions.
Definition at line 63 of file simulation.hpp.
References lb::lattice::get_node(), l, lb::lattice::nx, lb::lattice::ny, lb::node::rho(), lb::node::u(), and lb::node::v().
void lb::simulation::advect () [inline]
advect the populations
Include periodic boundary conditions here also
Definition at line 91 of file simulation.hpp.
Referenced by step().
void lb::simulation::write_fields () [inline]
write macroscopic variables to ascii file
Definition at line 140 of file simulation.hpp.
References l, output_index, and lb::lattice::write_fields().
Referenced by step().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const simulation & sim) [friend]
print to output stream
Definition at line 150 of file simulation.hpp.
The documentation for this class was generated from the following file:
simulation.hpp