LB2D: lb::detail::v9 Struct Reference
lb::detail::v9 Struct Reference
Lattice parameters for 9 velocity model.
#include <velocity_set.hpp>
Public Member Functions
void f_eq (float_type *f_eq, float_type rho, float_type u, float_type v) const
Compute equilibrium.
template<typename Node >
void equilibrate (Node &n, float_type rho, float_type u, float_type v) const
Equilibrate a node.
template<typename Node >
void equilibrate (Node &n) const
Equilibrate a node.
Public Attributes
const std::array< float_type, 9 > W = {{ 16.0/36, 4.0/36, 4.0/36, 4.0/36, 4.0/36, 1.0/36, 1.0/36, 1.0/36, 1.0/36}}
Lattice weights.
const std::array< std::array
< int, 9 >, 2 > c
Molecular velocities.
const float_type cs = 1.0/std::sqrt(3.0)
Speed of sound.
const unsigned int size = 9
Number of velocities.
Friends
const v9 & lb::velocity_set ()
Function for instantiating the singleton is a friend.
Detailed Description
Lattice parameters for 9 velocity model.
This class models a the singleton design pattern. That means there exists only one single instance throughout the lifetime of the program. To instantiate and access this object use the free function velocity_set.
This class holds parameters like lattice weights, molecular velocities and speed of sound. It also exposes member functions to compute the equilibrium populations.
Definition at line 34 of file velocity_set.hpp.
Member Function Documentation
void lb::detail::v9::f_eq (float_type * f_eq, float_type rho, float_type u, float_type v) const [inline]
Compute equilibrium.
Compute f_eq from the locally conserved quantities rho, u and v (see also v9::equilibrate).
Parameters:
[in,out] f_eq Pointer to an array of size 9 to store the computed values
[in] rho Local density
[in] u Local flow velocity in x-direction
[in] v Local flow velocity in y-direction
Definition at line 85 of file velocity_set.hpp.
References W.
Referenced by lb::simulation::collide(), and lb::H_root().
template<typename Node > void lb::detail::v9::equilibrate (Node & n, float_type rho, float_type u, float_type v) const [inline]
Equilibrate a node.
Compute f_eq from the locally conserved quantities rho, u and v and set the node's population to that equilibrium (see also v9::f_eq).
Template Parameters:
Node A node type
Parameters:
[in,out] n Reference to a Node object
[in] rho Local density
[in] u Local flow velocity in x-direction
[in] v Local flow velocity in y-direction
Definition at line 117 of file velocity_set.hpp.
References W.
Referenced by equilibrate(), and lb::simulation::initialize().
template<typename Node > void lb::detail::v9::equilibrate (Node & n) const [inline]
Equilibrate a node.
Compute f_eq from the locally conserved quantities rho, u and v and set the node's population to that equilibrium (see also v9::f_eq and v9::equilibrate). The locally conserved quantities are taken form the node object itself.
Template Parameters:
Node A node type
Parameters:
[in,out] n Reference to a Node object
Definition at line 147 of file velocity_set.hpp.
References equilibrate().
The documentation for this struct was generated from the following file:
velocity_set.hpp