LB2D: lb::node Struct Reference
lb::node Struct Reference
Node representing one lattice site.
#include <lattice.hpp>
Public Member Functions
node ()
Default constructor.
node (lattice *lat, int i, int j)
Construct from lattice and position.
void set (lattice *lat, int i, int j)
Set lattice and position.
float_type f (unsigned int i) const
Get population.
float_type & f (unsigned int i)
Get/set population.
float_type rho () const
Get density.
float_type & rho ()
Get/set density.
float_type u () const
Get x-velocity.
float_type & u ()
Get/set x-velocity.
float_type v () const
Get y-velocity.
float_type & v ()
Get/set y-velocity.
bool has_flag_property (std::string name) const
Query for flag property. Query whether a flag is set for the node.
bool set_flag_property (std::string name)
Set a flag Set the flag "name" to true.
bool unset_flag_property (std::string name)
Unset a flag Set the flag "name" to false.
bool has_data_property (std::string name) const
Query for data property. Query whether data property (object) is stored for the node.
template<typename T >
bool set_data_property (std::string name, const T &property)
Store a data property.
bool unset_data_property (std::string name)
Delete a data property.
template<typename T >
T & get_data_property (std::string name)
Get data property.
template<typename T >
const T & get_data_property (std::string name) const
Get data property.
Public Attributes
lattice * l
Pointer to a lattice object.
unsigned int index
Index for looking up data in the lattice.
coordinate< int > coord
Coordinate of node's position.
Detailed Description
Node representing one lattice site.
Easy access to bundled quantities and properties (works as proxy to the lattice class).
Definition at line 26 of file lattice.hpp.
Constructor & Destructor Documentation
lb::node::node (lattice * lat, int i, int j)
Construct from lattice and position.
Parameters:
[in] lat Pointer to the lattice
[in] i x coordinate
[in] j y coordinate
Precondition:
coordinates are in domain
Definition at line 360 of file lattice.hpp.
Member Function Documentation
void lb::node::set (lattice * lat, int i, int j)
Set lattice and position.
Parameters:
[in] lat Pointer to lattice
[in] i x coordinate
[in] j y coordinate
Precondition:
coordinates are in domain
Definition at line 363 of file lattice.hpp.
References lb::lattice::buffer_size, coord, lb::coordinate< T >::i, index, lb::coordinate< T >::j, l, and lb::lattice::real_nx.
float_type lb::node::f (unsigned int i) const [inline]
Get population.
Parameters:
i Population index
Returns:
Value of distribution function
Precondition:
population index exists
Definition at line 371 of file lattice.hpp.
References lb::lattice::f, index, and l.
float_type & lb::node::f (unsigned int i) [inline]
Get/set population.
Parameters:
i Population index
Returns:
Reference to value of distribution function
Precondition:
population index exists
Definition at line 372 of file lattice.hpp.
References lb::lattice::f, index, and l.
float_type lb::node::rho () const [inline]
Get density.
Returns:
Local density
Definition at line 373 of file lattice.hpp.
References index, l, and lb::lattice::rho.
Referenced by lb::simulation::initialize().
float_type & lb::node::rho () [inline]
Get/set density.
Returns:
Reference to local density
Definition at line 374 of file lattice.hpp.
References index, l, and lb::lattice::rho.
float_type lb::node::u () const [inline]
Get x-velocity.
Returns:
Local flow velocity in x direction
Definition at line 375 of file lattice.hpp.
References index, l, and lb::lattice::u.
Referenced by lb::simulation::initialize().
float_type & lb::node::u () [inline]
Get/set x-velocity.
Returns:
Reference to local flow velocity in x direction
Definition at line 376 of file lattice.hpp.
References index, l, and lb::lattice::u.
float_type lb::node::v () const [inline]
Get y-velocity.
Returns:
Local flow velocity in y direction
Definition at line 377 of file lattice.hpp.
References index, l, and lb::lattice::v.
Referenced by lb::simulation::initialize().
float_type & lb::node::v () [inline]
Get/set y-velocity.
Returns:
Reference to local flow velocity in y direction
Definition at line 378 of file lattice.hpp.
References index, l, and lb::lattice::v.
bool lb::node::has_flag_property (std::string name) const [inline]
Query for flag property. Query whether a flag is set for the node.
Parameters:
[in] name Flag name
Returns:
True if flag is set, otherwise false
Definition at line 380 of file lattice.hpp.
References lb::property_array::has_flag_property(), index, l, and lb::lattice::properties.
bool lb::node::set_flag_property (std::string name) [inline]
Set a flag Set the flag "name" to true.
Parameters:
[in] name Flag name
Returns:
True if flag exists, otherwise false
Definition at line 381 of file lattice.hpp.
References index, l, lb::lattice::properties, and lb::property_array::set_flag_property().
Referenced by lb::lattice::add_wall().
bool lb::node::unset_flag_property (std::string name) [inline]
Unset a flag Set the flag "name" to false.
Parameters:
[in] name Flag name
Returns:
True if flag exists, otherwise false
Definition at line 382 of file lattice.hpp.
References index, l, lb::lattice::properties, and lb::property_array::unset_flag_property().
bool lb::node::has_data_property (std::string name) const [inline]
Query for data property. Query whether data property (object) is stored for the node.
Parameters:
[in] name Data property name
Returns:
True if thre is such a data property, otherwise false
Definition at line 383 of file lattice.hpp.
References lb::property_array::has_data_property(), index, l, and lb::lattice::properties.
template<typename T > bool lb::node::set_data_property (std::string name, const T & property) [inline]
Store a data property.
Template Parameters:
T Type of the data property
Parameters:
[in] name Data property name
[in] property Data property object
Returns:
True if data property exists, otherwise false
Definition at line 385 of file lattice.hpp.
References index, l, lb::lattice::properties, and lb::property_array::set_data_property().
bool lb::node::unset_data_property (std::string name)
Delete a data property.
Parameters:
[in] name Data property name
Returns:
True if data property exists, otherwise false
Definition at line 386 of file lattice.hpp.
References index, l, lb::lattice::properties, and lb::property_array::unset_data_property().
template<typename T > T & lb::node::get_data_property (std::string name)
Get data property.
Template Parameters:
T Type of the data property
Parameters:
[in] name Data property name
Returns:
Reference to data property object
Definition at line 388 of file lattice.hpp.
References lb::property_array::get_data_property(), index, l, and lb::lattice::properties.
template<typename T > const T & lb::node::get_data_property (std::string name) const
Get data property.
Template Parameters:
T Type of the data property
Parameters:
[in] name Data property name
Returns:
Reference to data property object
Definition at line 390 of file lattice.hpp.
References lb::property_array::get_data_property(), index, l, and lb::lattice::properties.
The documentation for this struct was generated from the following file:
lattice.hpp